### ISSUE TITLE
[Docs]: Document quotas and limits

### ISSUE THREAD

**Issue by TomFern** [semaphoreci/semaphore#111]
### Type

Improvement idea

### What do you want to report?

Add quotas and limits for blocks, pipelines, queues, job execution and log size in their corresponding pages

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Review link: 
- https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/jobs%23limits
- https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/pipelines%23limits

**Comment by AleksandarCole** [comment]
Looks good 👍
