### ISSUE TITLE
[Docs]: Pages not loading - ChunkLoadError: Loading chunk 5453

### ISSUE THREAD

**Issue by AleksandarCole** [semaphoreci/semaphore#127]
### Type

Bug report

### What do you want to report?

Any page that I try to open fails to load with the error from the screenshot.
These pages were working as expected until 10min ago.

https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/jobs

![image](https://github.com/user-attachments/assets/0d14d1fd-f34c-4ea8-a106-60f2cb1ee471)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by DamjanBecirovic** [comment]
After the redeployment, we can no longer reproduce the bug. 
@AleksandarCole, can you please verify if it is solved for you as well?

**Comment by AleksandarCole** [comment]
Seems to be fixed now. @DamjanBecirovic thanks!
