### ISSUE TITLE
[Docs]: Mark Xcode14 as deprecated since end of september

### ISSUE THREAD

**Issue by TomFern** [semaphoreci/semaphore#176]
### Type

Improvement idea

### What do you want to report?

Mark Xcode14 as deprecated since end of september

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by pieterocp** [comment]
We can probably close from the PR.

As an aside, does semaphoreci do brownouts out all?

**Comment by TomFern** [comment]
@pieterocp yes, we do browouts for most potentially breaking changes
