### ISSUE TITLE
Support storing non-encrypted environment variables outside of the repository

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/semaphore#20]
Based on a question on community:

> Somewhat related, I'm also searching for how to manage environment variables. Not secret ones; generalized env vars used for per-project or global configuration that anyone in my org should be able to view or change. Most CIs (and Semaphore 1.0) allow these to be specified outside of the in-repo config file because it shouldn't take a code change to set up a new environment. Hoping this is possible!

**Comment by darkofabijan** [comment]
Secrets are the solution for this at the moment - https://docs.semaphoreci.com/article/66-environment-variables-and-secrets
