### ISSUE TITLE
Homebrew release for sem-cli

### ISSUE THREAD

**Issue by schliflo** [semaphoreci/semaphore#21]
As [Homebrew](https://brew.sh/) is a very popular package manager on macOS that most developers on macOs use I think this would be a good additional distribution path for the sem-cli.
They have detailed instructions on how to get something in their repos over here: https://docs.brew.sh/Formula-Cookbook

**Comment by michaelherold** [comment]
Here is a Homebrew package that I just put together:

```ruby
class SemaphoreCli < Formula
  desc "Semaphore 2.0 Command-line Interface"
  homepage "https://docs.semaphoreci.com/"
  url "https://storage.googleapis.com/sem-cli-releases/stable-darwin-amd64.tar.gz"
  sha256 "e7fd75a8a627cac80a7ead8ccd79b8d1b6e799a92c4e2203aff1db1b2de57ef9"
  version "0.8.2"

  def install
    bin.install "sem"
  end

  test do
    assert_equal "v0.8.2", system("sem", "version")
  end
end
```

Since this is a binary-only package, it won't be accepted into Homebrew proper. However, you can host your own tap very easily.

**Comment by CommanderK5** [comment]
@schliflo Thank you for opening this issue.

@michaelherold Thank you for your contribution to this issue.

Semaphore [cli](https://github.com/semaphoreci/cli) is now available to install over homebrew.

```bash
brew install semaphoreci/tap/sem
```
