### ISSUE TITLE
[Docs]: Update Curl example in API documentation

### ISSUE THREAD

**Issue by diegoguerrad** [semaphoreci/semaphore#215]
### Type

Bug report

### What do you want to report?

https://docs.semaphoreci.com/reference/api-v1alpha/#validating-a-pipeline-yaml
Curl example returns an error. This was reported in our internal SC 6813

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Can you share more details used? I just tested it on one of my project and my org. It works for me:

```shell
$ curl -i -X POST \
        -H "Authorization: Token <my-api-token>" \
        -H "Content-Type: application/json" \
        --data "{\"yaml_definition\": \"$(cat .semaphore/semaphore.yml | sed 's/\"/\\\"/g')\"}" \
        "https://tomfern.semaphoreci.com/api/v1alpha/yaml"

HTTP/2 200
cache-control: max-age=0, private, must-revalidate
content-length: 56
date: Fri, 06 Dec 2024 11:37:59 GMT
server: envoy
x-envoy-upstream-service-time: 16
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

{"pipeline_id":"","message":"YAML definition is valid."}
```

Reference page: https://docs.semaphoreci.com/reference/api#validate-a-pipeline-yaml

**Comment by diegoguerrad** [comment]
hi @TomFern I checked with the Tech guys and this should now be correct, so no need to update this anymore. Thanks for still checking on this🙇 we can close.
