### ISSUE TITLE
sem-cli: "error: unrecognized git remote format"

### ISSUE THREAD

**Issue by cboggs** [semaphoreci/semaphore#22]
Trying to `sem init` an existing repo, which contains two remotes in my local clone, I get the error:
```
error: unrecognized git remote format
```

sem-cli version: `v0.4.1`

There's not much special about my remotes as far as I can tell:
```
$ git remote -v
cboggs  git@github.com:cboggs/bomb-squad (fetch)
cboggs  git@github.com:cboggs/bomb-squad (push)
origin  git@github.com:Fresh-Tracks/bomb-squad (fetch)
origin  git@github.com:Fresh-Tracks/bomb-squad (push)
```

It appears to have still created `.semaphore/semaphore.yml`, but the error is unexpected.

**Comment by cboggs** [comment]
Just for extra detail, removing all remotes and re-adding just `origin` presents the same error, and thus I can't get Semaphore online to recognize the project.

**Comment by shiroyasha** [comment]
@cboggs Thank you for opening this issue.

Currently the CLI accepts only git remotes in the following format: `git@github.com:<owner>/<username>.git`. In your case this would be `git@github.com:cboggs/bomb-squad.git`.

We plan to tackle this issue in the next release of sem CLI.

**Comment by cboggs** [comment]
Thanks! I'll close this as there's already a work item planned.
