### ISSUE TITLE
[Docs]: Improvement for "How to invite users" page

### ISSUE THREAD

**Issue by diegoguerrad** [semaphoreci/semaphore#238]
### Type

Improvement idea

### What do you want to report?

Link to section: https://docs.semaphoreci.com/using-semaphore/organizations#add-people
Section:

Notes to update:

Option A: By their GitHub handle
<img width="239" alt="image" src="https://github.com/user-attachments/assets/7e198f00-0783-4e1b-a3fc-5a919fbb07a8">

- I believe this option does not allow us to send an email notification.
I'd suggest specifying that emails can't be sent with this option. 
- Users sometimes get confused and attempt to add members using their emails, which does not work.
I'd suggest highlighting this. 

Option A and B:
- For both options, the sync between GH and Semaphore could take some time or present an issue as with any others. We sometimes get tickets from customers reporting a user hasn't yet been added - the "refresh" button tends to 
I'd suggest including the refresh button as part of the instructions. 

Improvement draft idea: please make any needed changes to the wording or structure

How to invite users
To invite a user to your organization, press the Add people button. You have two options:

- By their GitHub handle

  - Type their GitHub handle and press Invite. 
  - Note: this field does not allow email addresses and doesn't send email notifications to users. To notify users via email, use the option below. 

- By existing projects

  The list shows GitHub and BitBucket users that already have access to repositories but have not yet been added to the Semaphore project

  1.Select the users and optionally type an email
  2.Press **Add selected** to add them to the organization and project
  
In case of delays, click on the "Refresh" button in the top right corner of the page after sending an invite. This will trigger a sync between GitHub and Semaphore, which can typically last up to 2-5min. 

![image](https://github.com/user-attachments/assets/93bcb2e2-3199-499a-8ab2-d9953b45cb1a)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Thank you @diegoguerrad. Good idea! I have added your suggestions to the organization page
