### ISSUE TITLE
[Docs]: Improvement on Contributing page - Forking the repo

### ISSUE THREAD

**Issue by mateuscap** [semaphoreci/semaphore#254]
### Type

Improvement idea

### What do you want to report?

There is a special section dedicated to [External Contributors](https://github.com/semaphoreci/semaphore/blob/main/docs/docs-contributing/CONTRIBUTING.md#external-contributors) in the Contribution Guidelines, but I believe it could be better placed, considering the instructions flow.

One of the following ideas should work:
- placing it before [Step 1: Set Up Your Local Environment](https://github.com/semaphoreci/semaphore/blob/main/docs/docs-contributing/CONTRIBUTING.md#step-1-set-up-your-local-environment)

or
- adding a note in the [prerequisites](https://github.com/semaphoreci/semaphore/blob/main/docs/docs-contributing/CONTRIBUTING.md#prerequisites) to address this case and direct the contributor to this section

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Thank you @mateuscap good idea. I've updated the guide to make it easier to use for external contributors.
