### ISSUE TITLE
[Docs]: Add info - 'set -e' will break debug session

### ISSUE THREAD

**Issue by mateuscap** [semaphoreci/semaphore#256]
### Type

New content idea

### What do you want to report?

This info might be interesting for the [FAQ](https://docs.semaphoreci.com/getting-started/faq) and/or the [Debugging jobs page](https://docs.semaphoreci.com/using-semaphore/jobs#debug-jobs).

Using 'set -e' command will not allow the user to use autocomplete(`tab` key) in the debug session. After setting this flag, using autocomplete(`tab` key) will close the session with an error, even if it is set from inside a bash script.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Pushed to prod
