### ISSUE TITLE
[Docs]: bad formatting in FAQ Pipelines section 

### ISSUE THREAD

**Issue by mateuscap** [semaphoreci/semaphore#257]
### Type

Bug report

### What do you want to report?

[Current version](https://github.com/semaphoreci/semaphore/commit/cb0c5a05d59865bdf11c3c0718cf203832170637) of this page contains a small issue with the note [here](https://docs.semaphoreci.com/getting-started/faq#why-does-my-job-fail-when-i-specify-exit-0-in-commands). 

<img width="781" alt="image" src="https://github.com/user-attachments/assets/d74d8907-4d57-4eeb-86f8-76902ee21104">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Thank you @mateuscap for spotting this 🙏

**Comment by TomFern** [comment]
Pushed to prod
