### ISSUE TITLE
[Docs]: Projects page - small typos

### ISSUE THREAD

**Issue by diegoguerrad** [semaphoreci/semaphore#259]
### Type

Improvement idea

### What do you want to report?

Projects page: https://docs.semaphoreci.com/using-semaphore/projects

1. [How manage access to projects](https://docs.semaphoreci.com/using-semaphore/projects#people) > How to manage access to projects

2. Under the "[How to manually add/remove members to projects](https://docs.semaphoreci.com/using-semaphore/projects#manual)" Section
See project roles for more information what actions can each role perform. > See project roles for more information on what actions each role can perform.

3. Under the "[Pre-flight checks](https://docs.semaphoreci.com/using-semaphore/projects#preflight)" section:
They checks allow you to define... > These checks allow you to define...

4. Under the "[How to configure status checks](https://docs.semaphoreci.com/using-semaphore/projects#status-checks)" section:
Semaphore only report status checks... > Semaphore only reports status checks...

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Thank you @diegoguerrad for spotting these 🙏. Fixed on #261

**Comment by TomFern** [comment]
Pushed to prod
