### ISSUE TITLE
[Docs]: Missing os_image codes

### ISSUE THREAD

**Issue by mateuscap** [semaphoreci/semaphore#262]
### Type

Bug report

### What do you want to report?

The docs present the existing images but not how to define them in the YAML files. It could be added, at least, to the [Machine Types](https://docs.semaphoreci.com/reference/machine-types) page:

Ubuntu 24.04 - `ubuntu2404`
Ubuntu 22.04 - `ubuntu2204`
Ubuntu 22.04 ARM - [I'm not sure if there's a specific name here] 
Ubuntu 20.04 - `ubuntu2004`

macOS Xcode 16 - `macos-xcode16`
macOS Xcode 15 - `macos-xcode15`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Pushed to prod
