### ISSUE TITLE
[Docs]: Missing "How to remove a user from an organization"

### ISSUE THREAD

**Issue by ivanaur** [semaphoreci/semaphore#273]
### Type

Bug report

### What do you want to report?

The old docs had sections:

1. How to remove a user from an organization
2. How to remove a user who has created a project from an organization

These sections should be added as they are also heavily used by the support team.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Pushed to prod

@ivanaur let me know what you think about the updated instructions, we can make corrections if needed: https://docs.semaphoreci.com/using-semaphore/organizations
