### ISSUE TITLE
Support for absolute paths in cache

### ISSUE THREAD

**Issue by mastilver** [semaphoreci/semaphore#28]
I have this job:
```
        - name: install terraform
          commands:
            - wget https://releases.hashicorp.com/terraform/0.7.12/terraform_0.7.12_linux_amd64.zip
            - unzip terraform_0.7.12_linux_amd64.zip -d ~/terraform
            - cache store terraform-0.7.12 ~/terraform
```

Then in another job, I have:
```
- cache restore terraform-0.7.12
```
I would expect this to put the `terraform` folder in `~/` (or `/home/semaphore`)
But instead, it's putting in `~/home/semaphore` (or `/home/semaphore/home/semaphore/`)

**Comment by mimimalizam** [comment]
Hi @mastilver, thanks for the feedback - much appreciated! 

At the moment `cache` uses `tar` when creating an archive. Consequently, `cache store` function is removing leading `/` from the specified `path`.  For the time being, I'd like to suggest mitigating this with `mv`.

**Comment by mimimalizam** [comment]
Hi @mastilver I just wanted to let you know that you can now use `cache` CLI as you've expected.

Running the following commands in Semaphore job

`cache store mykey ~/mystuff`
...
`cache restore mykey`

restores `mykey` archive and it's content is available at `/home/semaphore/mystuff/`

Feel free to let us know if you encounter any unexpected behavior.
