### ISSUE TITLE
[Docs]: Missing info - branch whitelisting behavior

### ISSUE THREAD

**Issue by mateuscap** [semaphoreci/semaphore#285]
### Type

Bug report

### What do you want to report?

The following information is missing.

Default behavior of branch whitelisting: _Whitelisting works only for newly-created branches, Semaphore will always create workflows for existing branches._ 

Here's the note from the [old docs](https://deprecated-docs.semaphoreci.com/essentials/project-workflow-trigger-options/#whitelisting-branches)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Pushed to prod
