### ISSUE TITLE
[Docs]: Java 21 isn't avaliable for Ubuntu 22.04

### ISSUE THREAD

**Issue by tbogosavljevic** [semaphoreci/semaphore#288]
### Type

Bug report

### What do you want to report?

As of now we do not support Java 21 on Ubuntu 22.04. We should remove this part of the documentation: https://docs.semaphoreci.com/reference/os-ubuntu#languages

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by tbogosavljevic** [comment]
I opened a PR to address this issue: https://github.com/semaphoreci/semaphore/pull/289

**Comment by d-stefanovic** [comment]
@tbogosavljevic 
Please check all other app versions, as I said in that support ticket this page took info from 24.04, I found some other wrong info there, not only for Java.

The source of truth is here:
https://github.com/semaphoreci/docs/blob/master/docs/ci-cd-environment/ubuntu-22.04-image.md

**Comment by d-stefanovic** [comment]
@TomFern @AleksandarCole 

I think this [os-ubuntu.md](https://github.com/semaphoreci/semaphore/blob/5e14b9ccbcda10b612172f6434913d0575178d4a/docs/docs/reference/os-ubuntu.md) shouldn't be organized like that, we maintain these version information here:

https://github.com/semaphoreci/docs/tree/master/docs/ci-cd-environment

![image](https://github.com/user-attachments/assets/6f3c871e-8a38-416b-bc7f-f31712ce5bb0)

So it looks like `os-ubuntu.md` will always have wrong info at some point, can we link it somehow to proper files?

**Comment by TomFern** [comment]
@tbogosavljevic please help me understand. Is the problem the structure of the document? Or that the information is not updated? Having one file per ubuntu version or putting everything in one file should not make much of a difference as long as it is well organized.

**Comment by tbogosavljevic** [comment]
I think @d-stefanovic means that one article per OS version should be the structure. Personally, I think either way is fine as long as the information is up-to-date. WDYT? I am not sure I am fully understanding either in this particular case

**Comment by TomFern** [comment]
IMO picking one files over many is a matter of choosing where to click for information. With multiple files, we need to pick the right OS version on the left sidebar. With one file, you can use the table on the right side of contents to pick your OS version.

Personally I think having everything in one file makes it easier to search in the page and easier to update multiple OS versions at once (search and replace in the editor), but it's a matter of taste at the end of the day. 

My original question was aimed at discovering if something is wrong with the structure. We can always change things but I need to know what's wrong with it.

**Comment by tbogosavljevic** [comment]
I agree with Tom here, especially considering that we are looking to get contributors involved in this project. One file will be easier to manage and keep up to date.
