### ISSUE TITLE
[Docs]: Improvement for "Can I change my VAT number?"

### ISSUE THREAD

**Issue by mrosatii** [semaphoreci/semaphore#291]
### Type

Improvement idea

### What do you want to report?

- Type
Improvement idea

- What do you want to report?
Link to section:  https://docs.semaphoreci.com/getting-started/faq#can-i-change-my-vat-number

- Notes to update:
While it's true that the customer can change the VAT number on their subscription by contacting the Account Support team, the documentation doesn't specify that the request must be made by the current owner or billing contact of the organization.

- Draft idea: _Please feel free to make any needed changes to the wording or structure._

**Can I change my VAT number?**

Not directly from the Semaphore website. After a subscription has been purchased, users can't add or change a VAT number (VAT ID) from the UI.

If you wish to change the VAT number associated with your subscription, please get in touch with [support@semaphoreci.com](mailto:support@semaphoreci.com) with the VAT number you want to add and we will gladly make it happen.

Please note that these requests must come from a user with Owner permissions, or from the current Billing contact associated with the organization’s FastSpring subscription. This is for security reasons, ensuring that only authorized individuals can make changes to the billing information.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Pushed to prod
