### ISSUE TITLE
[Docs]: Typo on the new user onboarding flow

### ISSUE THREAD

**Issue by diegoguerrad** [semaphoreci/semaphore#296]
### Type

Bug report

### What do you want to report?

A customer reported the following:

> "Create your first project by following these steps:
> • Look for the "+ Create new" button in the top right corner of your dashboard
> 
> The button is in the top left, not top right."

- This section seems to be correct now: https://docs.semaphoreci.com/getting-started/tour/hello-world
- This other section still displays it on the right instead of left: https://docs.semaphoreci.com/getting-started/changelog#week-of-october-5-2020:~:text=You%20can%20access%20this%20feature%20by%20clicking%20on%20the%20New%20project%20button%20in%20the%20top%20right%20corner.

But can you please help us check if there's any other section with this wording (in the top right corner)? It might be easier from your end than from the search bar. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Hi @diegoguerrad thanks for reporting. In which page did the customer find the error? I cannot find that exact string.

**Comment by diegoguerrad** [comment]
@TomFern thanks, I think that part might have already been corrected when you were updating the docs. 
Atm I think we only need to update this one (to left):

> This other section still displays it on the right instead of left: https://docs.semaphoreci.com/getting-started/changelog#week-of-october-5-2020:~:text=You%20can%20access%20this%20feature%20by%20clicking%20on%20the%20New%20project%20button%20in%20the%20top%20right%20corner.

I also tried to search for the exact strings and nothing else other than that one.

**Comment by TomFern** [comment]
Pushed to prod
