### ISSUE TITLE
[Docs]: Typos on "Role Based Access Control" page

### ISSUE THREAD

**Issue by diegoguerrad** [semaphoreci/semaphore#320]
### Type

Bug report

### What do you want to report?

Small typos on https://docs.semaphoreci.com/using-semaphore/rbac:

1. This page describes gives an overview of RBAC, how to assign roles to users and groups, and how to create custom roles. > This page gives an overview of RBAC, how to assign roles to users and groups, and how to create custom roles.

2. Semaphore uses a RBAC mode > Semaphore uses an RBAC mode

3. For example, let's say Pam has [admin](https://docs.semaphoreci.com/using-semaphore/rbac#org-admin) role > For example, let's say Pam has an admin role

4. If Kevin gives her the [reader](https://docs.semaphoreci.com/using-semaphore/rbac#project-reader) role in one project, she is still effectively admin in that project. > If Kevin gives her the [reader](https://docs.semaphoreci.com/using-semaphore/rbac#project-reader) role in one project, she will still be effectively an admin in that project. 

5. In addition to the pre-defined roles provided by Semaphore, you can create your custom own roles. > In addition to the pre-defined roles provided by Semaphore, you can create your own custom roles.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Thank you @diegoguerrad I fixed the typos on #321
