### ISSUE TITLE
Fast failing & cancelation strategies

### ISSUE THREAD

**Issue by nickluger** [semaphoreci/semaphore#34]
First, thank you for the amazing, thoughtful and sophisticated Semaphore 2.0. While version 1.0 was already great, 2.0 became by far the best CI in the world (for me).🥰

Now to the issue:
On version 1.0 we could configure options like "_fast failing enabled for all branches_" or" _cancel queued and started builds_" etc. Is still possible for 2.0? If i overlooked it to the docs, please point me there.

**Comment by weshooper** [comment]
💯 agree with above! 😃

**Comment by wojtekidd** [comment]
Hi @nickluger @weshooper and thank you for the feedback! 
Feel free to let me know your postal addresses so that we can send you some Semaphore stickers as a thank you gift - just drop a line to [outreach@semaphoreci.com](mailto:outreach@semaphoreci.com) and I'll take care of the rest.

**Comment by stom01** [comment]
Did this get resolved? I'm migrating to Semaphore 2.0 from Classic, and also would like to enable _cancel queued and started builds` as a cancellation strategy in Semaphore 2.0

**Comment by weshooper** [comment]
@stom01 not yet :-( I occasionally (rarely remember tbh) hit the Stop Build button if I notice. Our team are trying to get in the habit of including `[skip ci]` in commit messages when pushing changes if we suspect having additional changes to push shortly. Neither are ideal as they rely on busy minds remembering to do something (compared to the handy automated feature in Classic) but can help avoid the additional cost the redundant builds incur.

**Comment by Ivana-Markovic** [comment]
:tada: both Fast failing & Cancelation strategies (aka Auto-Cancel) have been released!

Please check our docs for more info:

**Fail Fast** 

- https://docs.semaphoreci.com/article/151-fail-fast-stop-running-tests-on-the-first-failure

**Cancelation strategies (aka Auto-Cancel)**
- https://docs.semaphoreci.com/article/50-pipeline-yaml#auto_cancel
- https://docs.semaphoreci.com/article/153-auto-cancel
