### ISSUE TITLE
[Docs]: Promotions Page - Review

### ISSUE THREAD

**Issue by AleksandarCole** [semaphoreci/semaphore#46]
### Type

Maintenance task

### What do you want to report?

Help us by reviewing the Promotions page:
https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/promotions

Read the [Review Guide](https://github.com/semaphoreci/semaphore/blob/main/docs/docs-contributing/REVIEWING.md) to get more information on what to focus on when reviewing the documentation pages. 

Use the following checklist to ensure you've covered all the steps:

- [ ] The page is clear and comprehensible
- [ ] No information is missing
- [ ] All examples and code snippets have been tested and are working
- [ ] Language and formatting match the [Style Guide](https://github.com/semaphoreci/semaphore/blob/main/docs/docs-contributing/STYLE_GUIDE.md)
- [ ] There are no broken links and page is properly segmented and easy to navigate
- [ ] Final report has been submitted in this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by csidyel** [comment]
PR: https://github.com/semaphoreci/semaphore/pull/179

### Broken links:

- [pipelines](https://storage.googleapis.com/sem-docs/main/index.html#/pipelines) 
- [project](https://storage.googleapis.com/sem-docs/main/index.html#/projects)
- [jobs](https://storage.googleapis.com/sem-docs/main/index.html#/jobs)
- [initialization job](https://storage.googleapis.com/sem-docs/main/index.html#/pipelines#init-job) 
- [environment variables](https://storage.googleapis.com/sem-docs/main/index.html#/jobs#environment-variables)
- [secret in the job](https://storage.googleapis.com/sem-docs/main/index.html#/jobs#secrets)
- [secrets](https://storage.googleapis.com/sem-docs/main/index.html#/secrets)
- [agent](https://storage.googleapis.com/sem-docs/main/index.html#/pipelines#agents)
- [workflow](https://storage.googleapis.com/sem-docs/main/index.html#/workflows)
- [Plan job and block execution with pipelines](https://storage.googleapis.com/sem-docs/main/index.html#/pipelines)
