### ISSUE TITLE
Slack Notifications

### ISSUE THREAD

**Issue by haideritx** [semaphoreci/semaphore#52]
For some reason slack notifications are not working.

What i want to have is, if any branch that for every build that is happening on semaphore 2.0 i should receive slack notification and should be for all statuses such as success/failed etc.

For that reason i tried through sem commands, i even tried through GUI of semaphore2.0.

Nothing seems to be affecting it.

In old semaphore there was option for a Test button, that when pressed a sample notification was sent to the slack. but there is no such button or trigger here. so i have to rebuild or push again with more changes to the github in order to run the build.

I have attached two images for the two configurations i have for my project. but none of them is working, not sure why i am not getting any notifications on slack.

![image](https://user-images.githubusercontent.com/26646476/63915257-fd73df00-ca4e-11e9-8320-528eee0bcecd.png)

![image](https://user-images.githubusercontent.com/26646476/63915307-167c9000-ca4f-11e9-84cc-599ce4401d42.png)

**Comment by haideritx** [comment]
Issue Resolved was a silly mistake. Added a wrong project name.

**Comment by Chrisissorry** [comment]
If somebody comes across this. I've also battled the settings for quite a while. `Results` is marked as optional, I expected the default to include all states. Actually, if you do not enter anything in `Results`, you won't get notifications.
