### ISSUE TITLE
Expired Slack invite URL

### ISSUE THREAD

**Issue by JakeHedman** [semaphoreci/semaphore#55]
The slack invite link in the README has expired: https://semaphorecommunity.slack.com/join/shared_invite/enQtMzk1MzI5NjE4MjI5LWY3Nzk4ZGM2ODRmMDVjYmIwZGFhMWI0ZDYyOWIxMGI1ZjFlODU1OTZiZWM3OGVkZjBmMWRiNWYzNjA4MjM2MTA

**Comment by Ivana-Markovic** [comment]
Thank you for letting us know Jake, this has been fixed and the README link has been updated: https://join.slack.com/t/semaphorecommunity/shared_invite/enQtMzk1MzI5NjE4MjI5LTg3MDcyNTg0ZWFjNTI1Y2U1NGEyZDBlNjhlZGM0ZjcxMmMxZDY5ZGYzM2RkM2VhNzgzNzI3YTk5ZDIzZjdhNGM
