### ISSUE TITLE
[Docs]: Initialization jobs

### ISSUE THREAD

**Issue by TomFern** [semaphoreci/semaphore#60]
### Type

Improvement idea

### What do you want to report?

Initialization jobs are not explained in detail. We should explain how they work in the pipeline pages. Explain when and what they run. Add a link from Organizations > Initialization Jobs to the new explanation.

The concept of the initialization job should be covered on the pipeline page:

When does it run? 
What does it do?  Clone repo, gets the yaml?
Mention esp which is open source
Mention the compilation/parse step of the yaml
Be more detailed, and technical. We may need to touch base with engineering/product for this.

The current docs also don't cover the details:
https://docs.semaphoreci.com/reference/pipeline-initialization/ 

Background: The initialization job under Organization settings was introduced for on-prem folks because the default machine is not available there.

The main pipeline initialization explanation should go into `using-semaphore/pipelines.md#pipeline-initialization`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AleksandarCole** [comment]
Link reviewed: https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/pipelines#init-job
No changes needed.
