### ISSUE TITLE
Build failing due to packagecloud: Payment required

### ISSUE THREAD

**Issue by Baklap4** [semaphoreci/semaphore#67]
Within our linux build scripts we're running an `sudo apt get update && sudo apt install some-deps` but didn't add special keys and such. Yesterday build were going alright, but today we seem to hit some errors upon `sudo apt get update`

```
E: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/bionic/InRelease  402  Payment Required [IP: 54.183.38.243 443]00:09
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease' is no longer signed.
```

Our semaphore CI file can be found here: https://github.com/performous/performous/blob/master/.semaphore/semaphore.yml

we are running:
```
machine:
    type: e1-standard-2
    os_image: ubuntu1804
```

**Comment by Ivana-Markovic** [comment]
Thank you for contacting us, @Baklap4 

We have identified an issue with the apt-get update and our team is working on fixing it. You can find more info and a workaround for the issue on our [status page](https://status.semaphoreci.com/).

Apologies for the inconvenience this might have caused you, please let me know if you have any additional questions or comments.

**Comment by Baklap4** [comment]
@Ivana-Markovic It's fixed upstream. Thanks for the quick response!
