### ISSUE TITLE
[Docs]: Pre-flight check page

### ISSUE THREAD

**Issue by TomFern** [semaphoreci/semaphore#79]
### Type

New content idea

### What do you want to report?

We need a page describing pre-flight checks

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by AleksandarCole** [comment]
1. **Overview** > Expand a bit on what preflight check is - it's a job that runs before every pipeline in your org, if it fails pipeline won't start. Only have 1 warning.
2. **Restricting who can start promotions** > You can achieve the same result with Deployment Targets
3. **Permissions required** > Let's remove this section from the docs

**Comment by TomFern** [comment]
Review links: 
- project: https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/projects%23preflight
- organization: https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/org-preflight

**Comment by TomFern** [comment]
Fixed on #148

**Comment by AleksandarCole** [comment]
Looks good 👍 

Slight suggestion added: https://github.com/semaphoreci/semaphore/pull/148#discussion_r1713659386
Please close this ticket once reviewing the suggested change.
