### ISSUE TITLE
[Docs]: OpenID connect page

### ISSUE THREAD

**Issue by TomFern** [semaphoreci/semaphore#80]
### Type

New content idea

### What do you want to report?

We need an OpenID connect page

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by AleksandarCole** [comment]
Reviewed: https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/openid
Looks good.
