### ISSUE TITLE
[Docs]: Monorepo page

### ISSUE THREAD

**Issue by TomFern** [semaphoreci/semaphore#81]
### Type

New content idea

### What do you want to report?

We need a Monorepo page explaining change_in

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by AleksandarCole** [comment]
1. **INFO** - Reword so it doesn't sound like you need to add initialisation job
2. Change INFO to NOTE annotation type
3. Add`{default_branch: 'main'}` to all examples, even if we don't have to be explicit if branch is master.

**Comment by TomFern** [comment]
Review link: https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/optimization/monorepo

**Comment by TomFern** [comment]
Fixed on #149

**Comment by AleksandarCole** [comment]
Looks good 👍
