### ISSUE TITLE
[Docs]: Self-hosted agents page

### ISSUE THREAD

**Issue by TomFern** [semaphoreci/semaphore#82]
### Type

New content idea

### What do you want to report?

We need a page explaining Self-hosted agents

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Review links:
- https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/self-hosted
- https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/self-hosted-install
- https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/self-hosted-configure
- https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/self-hosted-aws
- https://storage.googleapis.com/sem-docs/main/index.html#/docs/reference/self-hosted-config

**Comment by AleksandarCole** [comment]
Amazing work 👏 

Added a very small formatting adjustment: https://github.com/semaphoreci/semaphore/pull/155

Please close the ticket after PR review.
