### ISSUE TITLE
[Docs]: Explain job matrix

### ISSUE THREAD

**Issue by TomFern** [semaphoreci/semaphore#83]
### Type

Improvement idea

### What do you want to report?

We need to explain how job matrix works. Could be in the jobs page

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Review link: https://storage.googleapis.com/sem-docs/main/index.html#/docs/using-semaphore/jobs%23matrix

**Comment by AleksandarCole** [comment]
Looks good 👍
