### ISSUE TITLE
[Docs]: Links leading to the same URL

### ISSUE THREAD

**Issue by ivanaur** [semaphoreci/semaphore#90]
### Type

Bug report

### What do you want to report?

All three links on the Contributing page [here](https://github.com/semaphoreci/semaphore/blob/main/docs/docs-contributing/CONTRIBUTING.md#provide-feedback) lead to the same URL: https://github.com/semaphoreci/semaphore/tree/main/docs/docs-contributing

> If you want to contribute by providing feedback, you can:
> 
> 1. Report an inaccuracy, lack of clarity, or missing information: [new issue template](https://github.com/semaphoreci/semaphore/blob/main/docs/docs-contributing)
> 2. Discuss the current state of the content or ask for clarification on any topic: [new discussion](https://github.com/semaphoreci/semaphore/blob/main/docs/docs-contributing)
> 3. Propose a new topic, page, or section: [new content proposal template](https://github.com/semaphoreci/semaphore/blob/main/docs/docs-contributing)

Not sure if this is the intended behavior.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Fixed on #187
